### PR TITLE
just try importing gpkitmodels

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
ok, it's working now. I also had to change this back so that coverage in installed in the virtualenv. If coverage is installed as a system package, it ends up using the system python rather than the virtualenv python.

**Comment by bqpd** [comment]
Closing because this PR was just to test fixes.

**Pull request closed without merging**
