### PR TITLE
Don't assume mosek is installed...

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by bqpd** [comment]
@whoburg, we're seeing failures in check_solution whenever MOSEK is not the solver. It's pretty clear that tolerance is too high...

(this is a GP, so I'm pretty sure we trust the solvers on these)

[cvxopt](https://acdl.mit.edu/csi/job/gpkit_ResearchModel_jho_PR/3/buildnode=macys,optimizer=mosek/testReport/junit/gpkit.tests.from_paths/TestFiles/test_modelgasmaleperfpy_mosek_cli/)
`Primal solution violates constraint: 1.00003344049 is greater than 1.`

[mosek_cli](https://acdl.mit.edu/csi/job/gpkit_ResearchModel_jho_PR/3/buildnode=macys,optimizer=mosek/testReport/junit/gpkit.tests.from_paths/TestFiles/test_modelgasmaleperfpy_mosek_cli/)
`Primal solution violates constraint: 1.0001143697 is greater than 1.`

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
It passes, yay!

**Comment by whoburg** [comment]
so mosek gets a different answer than mosek_cli?

The key question is why the solvers are returning solutions that violate their own tolerance settings (as we understand them). My guess is that we don't understand the settings correctly, but we need to understand what's going on there to make an informed decision on the check_solution tolerance.

**Comment by bqpd** [comment]
It gets a different constraint solution, but I'll check how different the costs are.

**Comment by bqpd** [comment]
| solver | cost |
| -------- | ------ |
| mosek | 0.172329218038 |
| mosek_cli | 0.1723292 |
| cvxopt | 0.172329218038 |

```
Using solver 'mosek'
Solving for 704 variables.
Solving took 0.151 seconds.
Allowing negative dual variable(s) as small as -2.78457812364e-13.
0.172329218038 1 / day
```

```
Using solver 'mosek_cli'
Solving for 704 variables.
Solving took 0.159 seconds.
Allowing negative dual variable(s) as small as -2.81903e-13.
Warning: Constraint [z_{bre}_Mission, Climb, FlightSegment, BreguetEndurance_(7,)... >= 2.45*BSFC_Mission, Climb, FlightSegment, AircraftPerf, EnginePerf_(7,)*P_{total}_Mission, Climb, Fli...] is not tight because the left hand side evaluated to 0.00164611716106 but the right hand side evaluated to 0.00164611883964 dimensionless (Allowable error: 0.0001%, Actual error: 0.0001%)

0.1723292 1 / day
```

```
Using solver 'cvxopt'
Solving for 704 variables.
Solving took 116 seconds.
Warning: Constraint [z_{bre}_Mission, Climb, FlightSegment, BreguetEndurance_(0,)... >= 2.45*BSFC_Mission, Climb, FlightSegment, AircraftPerf, EnginePerf_(0,)*P_{total}_Mission, Climb, Fli...] is not tight because the left hand side evaluated to 0.00109722270863 but the right hand side evaluated to 0.00109721446158 dimensionless (Allowable error: 0.0001%, Actual error: 0.00075%)

Warning: Constraint [z_{bre}_Mission, Climb, FlightSegment, BreguetEndurance_(1,)... >= 2.45*BSFC_Mission, Climb, FlightSegment, AircraftPerf, EnginePerf_(1,)*P_{total}_Mission, Climb, Fli...] is not tight because the left hand side evaluated to 0.0011322231164 but the right hand side evaluated to 0.00113221544799 dimensionless (Allowable error: 0.0001%, Actual error: 0.00068%)

Warning: Constraint [z_{bre}_Mission, Climb, FlightSegment, BreguetEndurance_(2,)... >= 2.45*BSFC_Mission, Climb, FlightSegment, AircraftPerf, EnginePerf_(2,)*P_{total}_Mission, Climb, Fli...] is not tight because the left hand side evaluated to 0.00117475521507 but the right hand side evaluated to 0.00117474786602 dimensionless (Allowable error: 0.0001%, Actual error: 0.00063%)

Warning: Constraint [z_{bre}_Mission, Climb, FlightSegment, BreguetEndurance_(3,)... >= 2.45*BSFC_Mission, Climb, FlightSegment, AircraftPerf, EnginePerf_(3,)*P_{total}_Mission, Climb, Fli...] is not tight because the left hand side evaluated to 0.0012269790379 but the right hand side evaluated to 0.00122697194047 dimensionless (Allowable error: 0.0001%, Actual error: 0.00058%)

Warning: Constraint [z_{bre}_Mission, Climb, FlightSegment, BreguetEndurance_(4,)... >= 2.45*BSFC_Mission, Climb, FlightSegment, AircraftPerf, EnginePerf_(4,)*P_{total}_Mission, Climb, Fli...] is not tight because the left hand side evaluated to 0.00129243441548 but the right hand side evaluated to 0.00129242755946 dimensionless (Allowable error: 0.0001%, Actual error: 0.00053%)

Warning: Constraint [z_{bre}_Mission, Climb, FlightSegment, BreguetEndurance_(5,)... >= 2.45*BSFC_Mission, Climb, FlightSegment, AircraftPerf, EnginePerf_(5,)*P_{total}_Mission, Climb, Fli...] is not tight because the left hand side evaluated to 0.00137672058323 but the right hand side evaluated to 0.00137671399215 dimensionless (Allowable error: 0.0001%, Actual error: 0.00048%)

Warning: Constraint [z_{bre}_Mission, Climb, FlightSegment, BreguetEndurance_(6,)... >= 2.45*BSFC_Mission, Climb, FlightSegment, AircraftPerf, EnginePerf_(6,)*P_{total}_Mission, Climb, Fli...] is not tight because the left hand side evaluated to 0.00148912651437 but the right hand side evaluated to 0.00148912024451 dimensionless (Allowable error: 0.0001%, Actual error: 0.00042%)

Warning: Constraint [z_{bre}_Mission, Climb, FlightSegment, BreguetEndurance_(7,)... >= 2.45*BSFC_Mission, Climb, FlightSegment, AircraftPerf, EnginePerf_(7,)*P_{total}_Mission, Climb, Fli...] is not tight because the left hand side evaluated to 0.00164622415821 but the right hand side evaluated to 0.00164621828418 dimensionless (Allowable error: 0.0001%, Actual error: 0.00036%)

Warning: Constraint [z_{bre}_Mission, Climb, FlightSegment, BreguetEndurance_(8,)... >= 2.45*BSFC_Mission, Climb, FlightSegment, AircraftPerf, EnginePerf_(8,)*P_{total}_Mission, Climb, Fli...] is not tight because the left hand side evaluated to 0.00188070656045 but the right hand side evaluated to 0.00188070118239 dimensionless (Allowable error: 0.0001%, Actual error: 0.00029%)

0.172329383031 1 / day
```

**Comment by bqpd** [comment]
Looks like the costs are identical to 7 decimal places, but the constraints waver a bit...

**Pull request merged**
