### PR TITLE
trade study with high weight payload

### PR DESCRIPTION
**Pull request by mjburton11**
split performance number and trade study calcs to new file; high payload tex documentation

### CODE REVIEW

**Comment by mjburton11** [comment]
@galbramc @bqpd does this not have tests on PRs?

**Comment by bqpd** [comment]
it should : https://acdl.mit.edu/csi/job/gpkit_ResearchModel_jho_PR/
but it looks like it isn't triggering...

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
dere we go

**Comment by mjburton11** [comment]
test this please

**Comment by mjburton11** [comment]
@bqpd do I not have admin rights to initiate tests?

**Comment by mjburton11** [comment]
test this please

**Comment by bqpd** [comment]
hmm, if that were the case I think @acdl-jenkins would ask permission. @galbramc what's going on here?

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
(let the record show that this has entered testing only after my comment)

**Comment by bqpd** [comment]
let the record further show that this did _not_ test after my commit

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
...but did test once more after my comment

**Comment by mjburton11** [comment]
I got an email saying this failed, but it looks like this is still testing...

**Comment by mjburton11** [comment]
@bqpd I think my TESTCONFIG file has skip cvxopt, but I think this is testing with cvxopt.  am I seeing that correctly?

**Comment by bqpd** [comment]
To make Jenkins happy we insert a `test_dummy` when all solvers are skipped...and if you look into the tests run on cvxopt computers, that's the only one.

**Comment by mjburton11** [comment]
Oh got it

**Comment by mjburton11** [comment]
Why is this taking so long...

**Comment by mjburton11** [comment]
test this please

**Comment by mjburton11** [comment]
retest this please

**Comment by mjburton11** [comment]
@bqpd dahhh, not testing... :(

**Comment by galbramc** [comment]
@bqpd, you need to whitelist Mike by typing 'add to whitelist' in a comment. Only admins can whitelist people. This prevents anyone from just creating a pull request and executing code in jenkins without our approval.

Notice how acdl-jenkins asked 'Can one of the admins verify this patch?', that's because mike is not whitelisted.

**Comment by mjburton11** [comment]
@galbramc will someone have to add me to the whitelist every time I make a PR?

**Comment by bqpd** [comment]
add to whitelist

**Comment by bqpd** [comment]
test this please

**Comment by bqpd** [comment]
@mjburton11 I think it's at most once per repository...and you're on the other repos, so I might have just copied this one wrong

**Comment by mjburton11** [comment]
I've also being seeing this problem on gassolar

**Comment by galbramc** [comment]
@mjburton11, no you only need to be whitelisted once per repo. Whitelisting is permanent (unless we remove you inside the jenkins configuration). @bqpd, you can allow testing without whitelisting for a single PR with 'ok to test'

**Comment by mjburton11** [comment]
Thanks!

**Pull request merged**
